[project]
name = "equity_researcher"
version = "0.1.0"
description = "equity_researcher using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.14.5a2"
]

[project.scripts]
equity_researcher = "equity_researcher.main:run"
run_crew = "equity_researcher.main:run"
train = "equity_researcher.main:train"
replay = "equity_researcher.main:replay"
test = "equity_researcher.main:test"
run_with_trigger = "equity_researcher.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
